NAME := Dstr
SOURCES := funcs.cc Dstr.cc main.cc
CPLUSPLUS := 1
KVASIR_OPTIONS := --nesting-depth=4
DAIKON_OPTIONS := --config_option daikon.derive.Derivation.disable_derived_variables=0

include ../Makefile.common
