
diffs:
	${MAKE} -C option-tests diffs

update-goals:
	${MAKE} -C option-tests update-goals

.PHONY: all test clean
all:
	${MAKE} -C option-tests all
test:
	${MAKE} -C option-tests test
clean:
	${MAKE} -C option-tests clean
