###########################################################################

# Read Makefile.common for what all of this means
# Read source code javadoc for what this tests for.

MAIN_CLASS:=misc.Issue554
PROJECT_FILE:=Issue554
INST_FILES = misc.Issue554
NO_MERGE=1
NO_JML=1

include ../../Makefile.common
