###########################################################################

# Read Makefile.common for what all of this means

MAIN_CLASS:=six170.TinySetTester

# ESC_ON:=1

include ../../Makefile.common

#USER_CLUSTER_OPTIONS:=-a km -k 5

instrument-files-revise:
	echo "six170/TinySet.java" >| ${INST_LIST_FILE}
