NAME := flex-rothermel
SOURCES := flex.c
PROGRAM_ARGS := output n14.fl
EXTRA_OUTPUTS := output lex.yy.c
DTRACE_DIFF := dtrace-diff-fast.pl
COUNTS_ONLY := 1

include ../Makefile.common

flex: config.h flexdef.h parse.h version.h
