###########################################################################

# Read Makefile.common for what all of this means

MAIN_CLASS:=agora.AgoraTest

ESC_ON:=1

include ../../Makefile.common

instrument-files-revise:
	echo "agora/AgoraTest.java" >| ${INST_LIST_FILE}
