###########################################################################

# Read Makefile.common for what all of this means

MAIN_CLASS:=DataStructures/RedBlackTree
PROJECT_FILE:=rbt

include ../../Makefile.common

instrument-files-revise:
	rm -f ${INST_LIST_FILE}
	echo "DataStructures/RedBlackTree.java" > ${INST_LIST_FILE}
	echo "DataStructures/RedBlackNode.java" >> ${INST_LIST_FILE}

# In mernst's original tests, this example says:
# SKIP THIS: IT DEPENDS ON TREES
