###########################################################################

# Read Makefile.common for what all of this means

# MAIN_CLASS:=javautil.IteratorMicroBenchmark17
MAIN_CLASS:=javautil.ArrayList17Test

include ../../Makefile.common

instrument-files-revise:
	echo "javautil/AbstractList17.java javautil/ArrayList17.java" >| ${INST_LIST_FILE}
