NAME := FunctionNamesTest
CPLUSPLUS := 1
C_EXT := cpp
KVASIR_OPTIONS := --ppt-list-file=FunctionNamesTest.ppts --var-list-file=FunctionNamesTest.vars
SOURCES := FunctionNamesTest.cpp second_file.cpp

include ../Makefile.common
