#
# Include file that sets up the classpath
#

# Add the basic jars to the classpath if they aren't already there
ifeq "$(wildcard ${DAIKONDIR}/java/lib/daikon-util.jar)" "${DAIKONDIR}/java/lib/daikon-util.jar"
    CLASSPATH_JARS = :${DAIKONDIR}/java/lib/bcel-util-all-0.0.4.jar:${DAIKONDIR}/java/lib/commons-exec-1.3.jar:${DAIKONDIR}/java/lib/options-all-0.3.1.jar:${DAIKONDIR}/java/lib/plume-util-0.0.1.jar:${DAIKONDIR}/java/lib/daikon-util.jar:${DAIKONDIR}/java/lib/java-getopt.jar:${DAIKONDIR}/java/lib/junit-4.12.jar
endif

# Add necessary items to the classpath if they are not already there
ifneq (.:,$(findstring .:,$(subst ;,:,$(CLASSPATH))))
  CLASSPATH := .:$(CLASSPATH)
endif
ifneq (daikon/java:,$(findstring daikon/java:,$(CLASSPATH)))
    CLASSPATH := $(CLASSPATH):${DAIKONDIR}/java
endif
ifdef CLASSPATH_JARS
  ifneq (daikon-util.jar,$(findstring daikon-util.jar,$(CLASSPATH)))
    CLASSPATH := $(CLASSPATH):$(CLASSPATH_JARS)
  endif
endif

# On Cygwin, translate the classpath to Windows format.  Only do so if
# this has not already been done, which is determined by looking for
# semicolons (;) in the classpath.
ifeq (cygwin,$(OSTYPE))
  ifneq (;,$(findstring ;,$(CLASSPATH)))
    CLASSPATH := $(shell cygpath -pws "$(CLASSPATH)")
  endif
endif

export CLASSPATH
