#
# Include file that sets up the classpath
#

# Add the basic jars to the classpath if they aren't already there
ifeq "$(wildcard ${DAIKONDIR}/java/lib/daikon-util.jar)" "${DAIKONDIR}/java/lib/daikon-util.jar"
    CLASSPATH_JARS = ${DAIKONDIR}/java/lib/*.jar
endif

# Add necessary items to the classpath if they are not already there
ifneq (.:,$(findstring .:,$(subst ;,:,$(CLASSPATH))))
  CLASSPATH := .:$(CLASSPATH)
endif
ifneq (daikon/java:,$(findstring daikon/java:,$(CLASSPATH)))
    CLASSPATH := $(CLASSPATH):${DAIKONDIR}/java
endif
ifdef CLASSPATH_JARS
  ifneq (daikon-util.jar,$(findstring daikon-util.jar,$(CLASSPATH)))
    CLASSPATH := $(CLASSPATH):$(CLASSPATH_JARS)
  endif
endif

# On Cygwin, translate the classpath to Windows format.  Only do so if
# this has not already been done, which is determined by looking for
# semicolons (;) in the classpath.
ifeq (cygwin,$(OSTYPE))
  ifneq (;,$(findstring ;,$(CLASSPATH)))
    CLASSPATH := $(shell cygpath -pws "$(CLASSPATH)")
  endif
endif

export CLASSPATH
