###########################################################################

# Read Makefile.common for what all of this means

# To toggle original / edited test suite, edit the use_original flag
# in PolyCalc/PublicTest.java

MAIN_CLASS:=PolyCalc.PublicTest
#MAIN_CLASS:=PolyCalc.PublicTestAug

ESC_ON:=1

include ../../Makefile.common

#USER_CLUSTER_OPTIONS:=-a km -k 5

instrument-files-revise:
	echo "PolyCalc/RatNum.java" >| ${INST_LIST_FILE}
