.TH BUGTRACK "1" "March 2002" "Tools" Tools
.SH NAME
bugtrack \- simple bug-tracking database
.SH SYNOPSIS
\fBbugtrack\fR [\fB-new\fR] [\fB-list \fIn\fR] [\fB-edit \fIn\fR] [\fB-del \fIn\fR]
.SH DESCRIPTION
.PP
Bugtrack is a simple bug-tracking database.  It is a veneer over CVS, and 
uses one file per report, named
.IR bugXXXX ,
(where 
.I XXXX
is the bug-report's numeric ID). 
.TP
.B -new
Create a new report. The program will prompt for various required fields,
then invoke the user's editor for the description field.
The owner(s) of the bug-report are sent notification by email.
.TP
.B -list
List a brief summary of all live bug reports.
.TP
.B -show
Show in full the bug report whose ID is
.IR n ;
(equivalent to \fIcvs up; more bug<n>\fR).
.TP
.B -edit
Edit the bug report whose ID is 
.IR n .
The owner(s) of the bug-report are sent notification by email.
.TP
.B -del
Delete the bug report whose ID is
.IR n ;
Do not use this for closing a bug report; use
.B -edit
instead, and change the status to
.IR closed .
.SS Usage Tips
The
.I owner
of a report defaults to the user that created it, but any number of 
people can be named as owner; this allows the person reporting the bug
to "share" it with other users or someone who can fix it.
.PP
When a mod is made to fix a bug, the person applying the fix should
not close the bug report but mark it as
.BR fixed ;
the original creator should close the report once they have verified the
fix.
.PP
When making changes to a bug entry, unless you are the owner and sole
editor, put your username at the end of the new description, and use a
bullet point to start your text.
.SS Fields
\fBStatus ::= New | Open | Fixed | Notabug | Closed\fR
.br
\fBOwner ::= <email-addr> [ , <email-addr> ] ...\fR
.br
\fBSeverity ::= Lethal | Vexing | Boneheaded | RFE\fR
.br
\fBReproducible ::= Yes | No | Dunno\fR
.SH ENVIRONMENT
.TP
\fBEDITOR\fR
specifies the user's preferred editor.
.B vi
is used if this is unset.
.TP
\fBEMAIL\fR
specifies the user's email address. Defaults to 
.BR $USER .
.SH FILES
.I BUGNUMBER
sequence-number for the next new bug-report
.br
.I bug<XXXX>
bug-report files
.SH AUTHOR
.PP
Alan Donovan <adonovan@lcs.mit.edu>.
.SH BUGS
Format of report is too terse.
.SH COPYRIGHT
Copyright \(co 2002 Alan Donovan. This is free software; see the source
for copying conditions.  There is NO warranty; not even for
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
.BR cvs (1)
