###########################################################################

# Read Makefile.common for what all of this means

MAIN_CLASS:=FirstUnitTest
JUNIT:=org.junit.platform.console.ConsoleLauncher --disable-ansi-colors --disable-banner -c
NO_MERGE=1
NO_JML=1

# Override sources to draw from "."
SOURCES:=$(shell pwd)

include ../../Makefile.common

