###########################################################################

# Use ":=" so that the shell commands run only once.
ifeq ($(origin JAVA_HOME), undefined)
ifeq ($(shell uname), Darwin)
  JAVA_HOME := $(shell /usr/libexec/java_home)
  ifeq (${JAVA_HOME},)
    $(error /usr/libexec/java_home did not find a JDK; set JAVA_HOME)
  endif
else
ifeq ($(shell which javac > /dev/null 2>&1 && echo found || echo nonexistent), found)
  JAVA_HOME := $(shell readlink -f $(shell which javac) | sed "s:/bin/javac::")
else
  $(info Failure: Here is the output of: which javac)
  $(info $(shell which javac))
  $(error 'which javac' had exit status 1)
endif
endif
endif

# need junit.jar on classpath to compile all junit references
# explicit order is necessary to get versions built with JDK 8 not 5
JUNIT_CLASSPATH := ${DAIKONDIR}/java/lib/junit-4.13.2-Daikon.jar:${DAIKONDIR}/java/lib/hamcrest-core-1.3-Daikon.jar:${DAIKONDIR}/java/lib/*
JAVAC := $(JAVA_HOME)/bin/javac -cp .:$(JUNIT_CLASSPATH)
