###########################################################################

# Read Makefile.common for what all of this means

MAIN_CLASS:=six170.FixedSizeSetTester

DAIKON_OPTIONS:=--ppt-select-pattern="^six170\.FixedSizeSet[:\.]"

ESC_ON:=1

include ../../Makefile.common

instrument-files-revise:
	echo "six170/FixedSizeSet.java" >| ${INST_LIST_FILE}
