###########################################################################

# Read Makefile.common for what all of this means

MAIN_CLASS:=six170.HanoiMain
PROJECT_FILE:=Hanoi

ESC_ON:=1

include ../../Makefile.common

instrument-files-revise:
	rm -f ${INST_LIST_FILE}
	echo "six170/Hanoi.java" > ${INST_LIST_FILE}
