//
// Generated by JTB 1.1.2
//

package jtb.cparser.syntaxtree;

// Grammar production:
// f0 -> [ DeclarationSpecifiers() ]
// f1 -> Declarator()
// f2 -> [ DeclarationList() ]
// f3 -> CompoundStatement()
public class FunctionDefinition implements Node {
  static final long serialVersionUID = 20050923L;

   public NodeOptional f0;
   public Declarator f1;
   public NodeOptional f2;
   public CompoundStatement f3;

   public FunctionDefinition(NodeOptional n0, Declarator n1, NodeOptional n2, CompoundStatement n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public void accept(jtb.cparser.visitor.Visitor v) {
      v.visit(this);
   }
}
