//
// Generated by JTB 1.1.2
//

package jtb.cparser.syntaxtree;

// Grammar production:
// f0 -> <IDENTIFIER>
// f1 -> ( "," <IDENTIFIER> )*
public class IdentifierList implements Node {
  static final long serialVersionUID = 20050923L;

   public NodeToken f0;
   public NodeListOptional f1;

   public IdentifierList(NodeToken n0, NodeListOptional n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(jtb.cparser.visitor.Visitor v) {
      v.visit(this);
   }
}
