//
// Generated by JTB 1.1.2
//

package jtb.cparser.syntaxtree;

// Grammar production:
// f0 -> ( Statement() )+
public class StatementList implements Node {
  static final long serialVersionUID = 20050923L;

   public NodeList f0;

   public StatementList(NodeList n0) {
      f0 = n0;
   }

   public void accept(jtb.cparser.visitor.Visitor v) {
      v.visit(this);
   }
}
