//
// Generated by JTB 1.1.2
//

package jtb.cparser.syntaxtree;

// Grammar production:
// f0 -> ( <CONST> | <VOLATILE> )
public class TypeQualifier implements Node {
  static final long serialVersionUID = 20050923L;

   public NodeChoice f0;

   public TypeQualifier(NodeChoice n0) {
      f0 = n0;
   }

   public void accept(jtb.cparser.visitor.Visitor v) {
      v.visit(this);
   }
}
