
###########################################################################

# Read Makefile.common for what all of this means
# Read source code javadoc for what this tests for.

MAIN_CLASS:=misc.StaticInteresting
PROJECT_FILE:=StaticInteresting
INST_FILES = misc.StaticInteresting

# ESC_ON:=0
DAIKON_OPTIONS    = --config config.txt

include ../../Makefile.common
