###########################################################################

# Read Makefile.common for what all of this means

MAIN_CLASS:=DataStructures.LinkedListTest

#ESC_ON:=1

# USER_DAIKON_OPTIONS:=--ppt-select-pattern="^DataStructures\.LinkedList[:\.]"

include ../../Makefile.common

#USER_CLUSTER_OPTIONS:=-a km -k 5

instrument-files-revise:
	echo "DataStructures/LinkedList.java DataStructures/LinkedListItr.java DataStructures/ListNode.java" >| ${INST_LIST_FILE}
