###########################################################################

# Read Makefile.common for what all of this means

MAIN_CLASS:=javautil.ArrayList13Test

include ../../Makefile.common

instrument-files-revise:
	echo "javautil/AbstractList13.java javautil/ArrayList13.java" >| ${INST_LIST_FILE}
