###########################################################################

# Read Makefile.common for what all of this means

MAIN_CLASS:=PolyCalc.PublicTest

ESC_ON:=1

include ../../Makefile.common

instrument-files-revise:
	echo "PolyCalc/RatTermVec.java" >| ${INST_LIST_FILE}
