###########################################################################

# Read Makefile.common for what all of this means

MAIN_CLASS:=DataStructures.CursorListTest

include ../../Makefile.common

instrument-files-revise:
	echo "DataStructures/CursorList.java DataStructures/CursorListItr.java DataStructures/CursorNode.java" >| ${INST_LIST_FILE}

