all:
	cd .. && $(MAKE) all
	$(MAKE) gui

all_force:
	cd .. && $(MAKE) all_force

tags:
	cd .. && $(MAKE) tags

clean:
	cd .. && $(MAKE) clean

audit:
	cd .. && $(MAKE) audit

gui:	InvariantsGUI.class
#	cd ../..;  java daikon.gui.InvariantsGUI /g1/users/mhao/daikon/inv_files/dsaa.inv 2>&1 | grep -v Font
