###########################################################################

# Read Makefile.common for what all of this means

MAIN_CLASS:=misc.EncapsulateDowncast
PROJECT_FILE:=ed
INST_FILES = ^misc.

ESC_ON:=1

include ../../Makefile.common

#instrument-files-revise:
