decl-version 2.0

var-comparability implicit

ppt std.initialize()void:::ENTER
  ppt-type enter
  variable ::Cur_Vertical_Sep
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ::High_Confidence
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 2
  variable ::Two_of_Three_Reports_Valid
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 3
  variable ::Own_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Own_Tracked_Alt_Rate
    var-kind variable
    dec-type int
    rep-type int
    comparability 5
  variable ::Other_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Alt_Layer_Value
    var-kind variable
    dec-type int
    rep-type int
    comparability 6
  variable ::Positive_RA_Alt_Thresh
    var-kind variable
    dec-type int[]
    rep-type hashcode
    comparability 7
  variable ::Positive_RA_Alt_Thresh[..]
    var-kind array
    enclosing-var ::Positive_RA_Alt_Thresh
    array 1
    dec-type int[]
    rep-type int[]
    comparability 8[6]
  variable ::Up_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 8
  variable ::Down_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 8
  variable ::Other_RAC
    var-kind variable
    dec-type int
    rep-type int
    comparability 9
  variable ::Other_Capability
    var-kind variable
    dec-type int
    rep-type int
    comparability 10
  variable ::Climb_Inhibit
    var-kind variable
    dec-type int
    rep-type int
    comparability 11

ppt std.initialize()void:::EXIT1
  ppt-type subexit
  variable ::Cur_Vertical_Sep
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ::High_Confidence
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 2
  variable ::Two_of_Three_Reports_Valid
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 3
  variable ::Own_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Own_Tracked_Alt_Rate
    var-kind variable
    dec-type int
    rep-type int
    comparability 5
  variable ::Other_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Alt_Layer_Value
    var-kind variable
    dec-type int
    rep-type int
    comparability 6
  variable ::Positive_RA_Alt_Thresh
    var-kind variable
    dec-type int[]
    rep-type hashcode
    comparability 7
  variable ::Positive_RA_Alt_Thresh[..]
    var-kind array
    enclosing-var ::Positive_RA_Alt_Thresh
    array 1
    dec-type int[]
    rep-type int[]
    comparability 8[6]
  variable ::Up_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 8
  variable ::Down_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 8
  variable ::Other_RAC
    var-kind variable
    dec-type int
    rep-type int
    comparability 9
  variable ::Other_Capability
    var-kind variable
    dec-type int
    rep-type int
    comparability 10
  variable ::Climb_Inhibit
    var-kind variable
    dec-type int
    rep-type int
    comparability 11

ppt std.ALIM()int:::ENTER
  ppt-type enter
  variable ::Cur_Vertical_Sep
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ::High_Confidence
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 2
  variable ::Two_of_Three_Reports_Valid
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 3
  variable ::Own_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Own_Tracked_Alt_Rate
    var-kind variable
    dec-type int
    rep-type int
    comparability 5
  variable ::Other_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Alt_Layer_Value
    var-kind variable
    dec-type int
    rep-type int
    comparability 6
  variable ::Positive_RA_Alt_Thresh
    var-kind variable
    dec-type int[]
    rep-type hashcode
    comparability 7
  variable ::Positive_RA_Alt_Thresh[..]
    var-kind array
    enclosing-var ::Positive_RA_Alt_Thresh
    array 1
    dec-type int[]
    rep-type int[]
    comparability 8[6]
  variable ::Up_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 8
  variable ::Down_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 8
  variable ::Other_RAC
    var-kind variable
    dec-type int
    rep-type int
    comparability 9
  variable ::Other_Capability
    var-kind variable
    dec-type int
    rep-type int
    comparability 10
  variable ::Climb_Inhibit
    var-kind variable
    dec-type int
    rep-type int
    comparability 11

ppt std.ALIM()int:::EXIT2
  ppt-type subexit
  variable ::Cur_Vertical_Sep
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ::High_Confidence
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 2
  variable ::Two_of_Three_Reports_Valid
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 3
  variable ::Own_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Own_Tracked_Alt_Rate
    var-kind variable
    dec-type int
    rep-type int
    comparability 5
  variable ::Other_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Alt_Layer_Value
    var-kind variable
    dec-type int
    rep-type int
    comparability 6
  variable ::Positive_RA_Alt_Thresh
    var-kind variable
    dec-type int[]
    rep-type hashcode
    comparability 7
  variable ::Positive_RA_Alt_Thresh[..]
    var-kind array
    enclosing-var ::Positive_RA_Alt_Thresh
    array 1
    dec-type int[]
    rep-type int[]
    comparability 12[6]
  variable ::Up_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 12
  variable ::Down_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 12
  variable ::Other_RAC
    var-kind variable
    dec-type int
    rep-type int
    comparability 9
  variable ::Other_Capability
    var-kind variable
    dec-type int
    rep-type int
    comparability 10
  variable ::Climb_Inhibit
    var-kind variable
    dec-type int
    rep-type int
    comparability 11
  variable return
    var-kind return
    dec-type int
    rep-type int
    comparability 12

ppt std.Inhibit_Biased_Climb()int:::ENTER
  ppt-type enter
  variable ::Cur_Vertical_Sep
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ::High_Confidence
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 2
  variable ::Two_of_Three_Reports_Valid
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 3
  variable ::Own_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Own_Tracked_Alt_Rate
    var-kind variable
    dec-type int
    rep-type int
    comparability 5
  variable ::Other_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Alt_Layer_Value
    var-kind variable
    dec-type int
    rep-type int
    comparability 6
  variable ::Positive_RA_Alt_Thresh
    var-kind variable
    dec-type int[]
    rep-type hashcode
    comparability 7
  variable ::Positive_RA_Alt_Thresh[..]
    var-kind array
    enclosing-var ::Positive_RA_Alt_Thresh
    array 1
    dec-type int[]
    rep-type int[]
    comparability 8[6]
  variable ::Up_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 8
  variable ::Down_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 8
  variable ::Other_RAC
    var-kind variable
    dec-type int
    rep-type int
    comparability 9
  variable ::Other_Capability
    var-kind variable
    dec-type int
    rep-type int
    comparability 10
  variable ::Climb_Inhibit
    var-kind variable
    dec-type int
    rep-type int
    comparability 11

ppt std.Inhibit_Biased_Climb()int:::EXIT3
  ppt-type subexit
  variable ::Cur_Vertical_Sep
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ::High_Confidence
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 2
  variable ::Two_of_Three_Reports_Valid
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 3
  variable ::Own_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Own_Tracked_Alt_Rate
    var-kind variable
    dec-type int
    rep-type int
    comparability 5
  variable ::Other_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Alt_Layer_Value
    var-kind variable
    dec-type int
    rep-type int
    comparability 6
  variable ::Positive_RA_Alt_Thresh
    var-kind variable
    dec-type int[]
    rep-type hashcode
    comparability 7
  variable ::Positive_RA_Alt_Thresh[..]
    var-kind array
    enclosing-var ::Positive_RA_Alt_Thresh
    array 1
    dec-type int[]
    rep-type int[]
    comparability 12[6]
  variable ::Up_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 12
  variable ::Down_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 12
  variable ::Other_RAC
    var-kind variable
    dec-type int
    rep-type int
    comparability 9
  variable ::Other_Capability
    var-kind variable
    dec-type int
    rep-type int
    comparability 10
  variable ::Climb_Inhibit
    var-kind variable
    dec-type int
    rep-type int
    comparability 11
  variable return
    var-kind return
    dec-type int
    rep-type int
    comparability 12

ppt std.Non_Crossing_Biased_Climb()boolean:::ENTER
  ppt-type enter
  variable ::Cur_Vertical_Sep
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ::High_Confidence
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 2
  variable ::Two_of_Three_Reports_Valid
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 3
  variable ::Own_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Own_Tracked_Alt_Rate
    var-kind variable
    dec-type int
    rep-type int
    comparability 5
  variable ::Other_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Alt_Layer_Value
    var-kind variable
    dec-type int
    rep-type int
    comparability 6
  variable ::Positive_RA_Alt_Thresh
    var-kind variable
    dec-type int[]
    rep-type hashcode
    comparability 7
  variable ::Positive_RA_Alt_Thresh[..]
    var-kind array
    enclosing-var ::Positive_RA_Alt_Thresh
    array 1
    dec-type int[]
    rep-type int[]
    comparability 8[6]
  variable ::Up_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 8
  variable ::Down_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 8
  variable ::Other_RAC
    var-kind variable
    dec-type int
    rep-type int
    comparability 9
  variable ::Other_Capability
    var-kind variable
    dec-type int
    rep-type int
    comparability 10
  variable ::Climb_Inhibit
    var-kind variable
    dec-type int
    rep-type int
    comparability 11

ppt std.Non_Crossing_Biased_Climb()boolean:::EXIT4
  ppt-type subexit
  variable ::Cur_Vertical_Sep
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ::High_Confidence
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 2
  variable ::Two_of_Three_Reports_Valid
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 3
  variable ::Own_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Own_Tracked_Alt_Rate
    var-kind variable
    dec-type int
    rep-type int
    comparability 5
  variable ::Other_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Alt_Layer_Value
    var-kind variable
    dec-type int
    rep-type int
    comparability 6
  variable ::Positive_RA_Alt_Thresh
    var-kind variable
    dec-type int[]
    rep-type hashcode
    comparability 7
  variable ::Positive_RA_Alt_Thresh[..]
    var-kind array
    enclosing-var ::Positive_RA_Alt_Thresh
    array 1
    dec-type int[]
    rep-type int[]
    comparability 8[6]
  variable ::Up_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 8
  variable ::Down_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 8
  variable ::Other_RAC
    var-kind variable
    dec-type int
    rep-type int
    comparability 9
  variable ::Other_Capability
    var-kind variable
    dec-type int
    rep-type int
    comparability 10
  variable ::Climb_Inhibit
    var-kind variable
    dec-type int
    rep-type int
    comparability 11
  variable return
    var-kind return
    dec-type boolean
    rep-type int
    comparability 13

ppt std.Non_Crossing_Biased_Descend()boolean:::ENTER
  ppt-type enter
  variable ::Cur_Vertical_Sep
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ::High_Confidence
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 2
  variable ::Two_of_Three_Reports_Valid
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 3
  variable ::Own_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Own_Tracked_Alt_Rate
    var-kind variable
    dec-type int
    rep-type int
    comparability 5
  variable ::Other_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Alt_Layer_Value
    var-kind variable
    dec-type int
    rep-type int
    comparability 6
  variable ::Positive_RA_Alt_Thresh
    var-kind variable
    dec-type int[]
    rep-type hashcode
    comparability 7
  variable ::Positive_RA_Alt_Thresh[..]
    var-kind array
    enclosing-var ::Positive_RA_Alt_Thresh
    array 1
    dec-type int[]
    rep-type int[]
    comparability 8[6]
  variable ::Up_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 8
  variable ::Down_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 8
  variable ::Other_RAC
    var-kind variable
    dec-type int
    rep-type int
    comparability 9
  variable ::Other_Capability
    var-kind variable
    dec-type int
    rep-type int
    comparability 10
  variable ::Climb_Inhibit
    var-kind variable
    dec-type int
    rep-type int
    comparability 11

ppt std.Non_Crossing_Biased_Descend()boolean:::EXIT5
  ppt-type subexit
  variable ::Cur_Vertical_Sep
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ::High_Confidence
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 2
  variable ::Two_of_Three_Reports_Valid
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 3
  variable ::Own_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Own_Tracked_Alt_Rate
    var-kind variable
    dec-type int
    rep-type int
    comparability 5
  variable ::Other_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Alt_Layer_Value
    var-kind variable
    dec-type int
    rep-type int
    comparability 6
  variable ::Positive_RA_Alt_Thresh
    var-kind variable
    dec-type int[]
    rep-type hashcode
    comparability 7
  variable ::Positive_RA_Alt_Thresh[..]
    var-kind array
    enclosing-var ::Positive_RA_Alt_Thresh
    array 1
    dec-type int[]
    rep-type int[]
    comparability 8[6]
  variable ::Up_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 8
  variable ::Down_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 8
  variable ::Other_RAC
    var-kind variable
    dec-type int
    rep-type int
    comparability 9
  variable ::Other_Capability
    var-kind variable
    dec-type int
    rep-type int
    comparability 10
  variable ::Climb_Inhibit
    var-kind variable
    dec-type int
    rep-type int
    comparability 11
  variable return
    var-kind return
    dec-type boolean
    rep-type int
    comparability 13

ppt std.Own_Below_Threat()boolean:::ENTER
  ppt-type enter
  variable ::Cur_Vertical_Sep
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ::High_Confidence
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 2
  variable ::Two_of_Three_Reports_Valid
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 3
  variable ::Own_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Own_Tracked_Alt_Rate
    var-kind variable
    dec-type int
    rep-type int
    comparability 5
  variable ::Other_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Alt_Layer_Value
    var-kind variable
    dec-type int
    rep-type int
    comparability 6
  variable ::Positive_RA_Alt_Thresh
    var-kind variable
    dec-type int[]
    rep-type hashcode
    comparability 7
  variable ::Positive_RA_Alt_Thresh[..]
    var-kind array
    enclosing-var ::Positive_RA_Alt_Thresh
    array 1
    dec-type int[]
    rep-type int[]
    comparability 8[6]
  variable ::Up_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 8
  variable ::Down_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 8
  variable ::Other_RAC
    var-kind variable
    dec-type int
    rep-type int
    comparability 9
  variable ::Other_Capability
    var-kind variable
    dec-type int
    rep-type int
    comparability 10
  variable ::Climb_Inhibit
    var-kind variable
    dec-type int
    rep-type int
    comparability 11

ppt std.Own_Below_Threat()boolean:::EXIT6
  ppt-type subexit
  variable ::Cur_Vertical_Sep
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ::High_Confidence
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 2
  variable ::Two_of_Three_Reports_Valid
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 3
  variable ::Own_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Own_Tracked_Alt_Rate
    var-kind variable
    dec-type int
    rep-type int
    comparability 5
  variable ::Other_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Alt_Layer_Value
    var-kind variable
    dec-type int
    rep-type int
    comparability 6
  variable ::Positive_RA_Alt_Thresh
    var-kind variable
    dec-type int[]
    rep-type hashcode
    comparability 7
  variable ::Positive_RA_Alt_Thresh[..]
    var-kind array
    enclosing-var ::Positive_RA_Alt_Thresh
    array 1
    dec-type int[]
    rep-type int[]
    comparability 8[6]
  variable ::Up_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 8
  variable ::Down_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 8
  variable ::Other_RAC
    var-kind variable
    dec-type int
    rep-type int
    comparability 9
  variable ::Other_Capability
    var-kind variable
    dec-type int
    rep-type int
    comparability 10
  variable ::Climb_Inhibit
    var-kind variable
    dec-type int
    rep-type int
    comparability 11
  variable return
    var-kind return
    dec-type boolean
    rep-type int
    comparability 13

ppt std.Own_Above_Threat()boolean:::ENTER
  ppt-type enter
  variable ::Cur_Vertical_Sep
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ::High_Confidence
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 2
  variable ::Two_of_Three_Reports_Valid
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 3
  variable ::Own_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Own_Tracked_Alt_Rate
    var-kind variable
    dec-type int
    rep-type int
    comparability 5
  variable ::Other_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Alt_Layer_Value
    var-kind variable
    dec-type int
    rep-type int
    comparability 6
  variable ::Positive_RA_Alt_Thresh
    var-kind variable
    dec-type int[]
    rep-type hashcode
    comparability 7
  variable ::Positive_RA_Alt_Thresh[..]
    var-kind array
    enclosing-var ::Positive_RA_Alt_Thresh
    array 1
    dec-type int[]
    rep-type int[]
    comparability 8[6]
  variable ::Up_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 8
  variable ::Down_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 8
  variable ::Other_RAC
    var-kind variable
    dec-type int
    rep-type int
    comparability 9
  variable ::Other_Capability
    var-kind variable
    dec-type int
    rep-type int
    comparability 10
  variable ::Climb_Inhibit
    var-kind variable
    dec-type int
    rep-type int
    comparability 11

ppt std.Own_Above_Threat()boolean:::EXIT7
  ppt-type subexit
  variable ::Cur_Vertical_Sep
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ::High_Confidence
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 2
  variable ::Two_of_Three_Reports_Valid
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 3
  variable ::Own_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Own_Tracked_Alt_Rate
    var-kind variable
    dec-type int
    rep-type int
    comparability 5
  variable ::Other_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Alt_Layer_Value
    var-kind variable
    dec-type int
    rep-type int
    comparability 6
  variable ::Positive_RA_Alt_Thresh
    var-kind variable
    dec-type int[]
    rep-type hashcode
    comparability 7
  variable ::Positive_RA_Alt_Thresh[..]
    var-kind array
    enclosing-var ::Positive_RA_Alt_Thresh
    array 1
    dec-type int[]
    rep-type int[]
    comparability 8[6]
  variable ::Up_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 8
  variable ::Down_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 8
  variable ::Other_RAC
    var-kind variable
    dec-type int
    rep-type int
    comparability 9
  variable ::Other_Capability
    var-kind variable
    dec-type int
    rep-type int
    comparability 10
  variable ::Climb_Inhibit
    var-kind variable
    dec-type int
    rep-type int
    comparability 11
  variable return
    var-kind return
    dec-type boolean
    rep-type int
    comparability 13

ppt std.alt_sep_test()int:::ENTER
  ppt-type enter
  variable ::Cur_Vertical_Sep
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ::High_Confidence
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 2
  variable ::Two_of_Three_Reports_Valid
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 3
  variable ::Own_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Own_Tracked_Alt_Rate
    var-kind variable
    dec-type int
    rep-type int
    comparability 5
  variable ::Other_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Alt_Layer_Value
    var-kind variable
    dec-type int
    rep-type int
    comparability 6
  variable ::Positive_RA_Alt_Thresh
    var-kind variable
    dec-type int[]
    rep-type hashcode
    comparability 7
  variable ::Positive_RA_Alt_Thresh[..]
    var-kind array
    enclosing-var ::Positive_RA_Alt_Thresh
    array 1
    dec-type int[]
    rep-type int[]
    comparability 8[6]
  variable ::Up_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 8
  variable ::Down_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 8
  variable ::Other_RAC
    var-kind variable
    dec-type int
    rep-type int
    comparability 9
  variable ::Other_Capability
    var-kind variable
    dec-type int
    rep-type int
    comparability 10
  variable ::Climb_Inhibit
    var-kind variable
    dec-type int
    rep-type int
    comparability 11

ppt std.alt_sep_test()int:::EXIT8
  ppt-type subexit
  variable ::Cur_Vertical_Sep
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ::High_Confidence
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 2
  variable ::Two_of_Three_Reports_Valid
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 3
  variable ::Own_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Own_Tracked_Alt_Rate
    var-kind variable
    dec-type int
    rep-type int
    comparability 5
  variable ::Other_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Alt_Layer_Value
    var-kind variable
    dec-type int
    rep-type int
    comparability 6
  variable ::Positive_RA_Alt_Thresh
    var-kind variable
    dec-type int[]
    rep-type hashcode
    comparability 7
  variable ::Positive_RA_Alt_Thresh[..]
    var-kind array
    enclosing-var ::Positive_RA_Alt_Thresh
    array 1
    dec-type int[]
    rep-type int[]
    comparability 8[6]
  variable ::Up_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 8
  variable ::Down_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 8
  variable ::Other_RAC
    var-kind variable
    dec-type int
    rep-type int
    comparability 9
  variable ::Other_Capability
    var-kind variable
    dec-type int
    rep-type int
    comparability 10
  variable ::Climb_Inhibit
    var-kind variable
    dec-type int
    rep-type int
    comparability 11
  variable return
    var-kind return
    dec-type int
    rep-type int
    comparability 13

ppt std.main(int;char\_**;)int:::ENTER
  ppt-type enter
  variable argc
    var-kind variable
    dec-type int
    rep-type int
    comparability 14
  variable argv
    var-kind variable
    dec-type char\_*[]
    rep-type hashcode
    comparability 15
  variable ::Cur_Vertical_Sep
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ::High_Confidence
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 2
  variable ::Two_of_Three_Reports_Valid
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 3
  variable ::Own_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Own_Tracked_Alt_Rate
    var-kind variable
    dec-type int
    rep-type int
    comparability 5
  variable ::Other_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Alt_Layer_Value
    var-kind variable
    dec-type int
    rep-type int
    comparability 6
  variable ::Positive_RA_Alt_Thresh
    var-kind variable
    dec-type int[]
    rep-type hashcode
    comparability 7
  variable ::Positive_RA_Alt_Thresh[..]
    var-kind array
    enclosing-var ::Positive_RA_Alt_Thresh
    array 1
    dec-type int[]
    rep-type int[]
    comparability 8[6]
  variable ::Up_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 8
  variable ::Down_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 8
  variable ::Other_RAC
    var-kind variable
    dec-type int
    rep-type int
    comparability 9
  variable ::Other_Capability
    var-kind variable
    dec-type int
    rep-type int
    comparability 10
  variable ::Climb_Inhibit
    var-kind variable
    dec-type int
    rep-type int
    comparability 11

ppt std.main(int;char\_**;)int:::EXIT9
  ppt-type subexit
  variable argc
    var-kind variable
    dec-type int
    rep-type int
    comparability 14
  variable argv
    var-kind variable
    dec-type char\_*[]
    rep-type hashcode
    comparability 15
  variable ::Cur_Vertical_Sep
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ::High_Confidence
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 2
  variable ::Two_of_Three_Reports_Valid
    var-kind variable
    dec-type boolean
    rep-type int
    comparability 3
  variable ::Own_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Own_Tracked_Alt_Rate
    var-kind variable
    dec-type int
    rep-type int
    comparability 5
  variable ::Other_Tracked_Alt
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable ::Alt_Layer_Value
    var-kind variable
    dec-type int
    rep-type int
    comparability 6
  variable ::Positive_RA_Alt_Thresh
    var-kind variable
    dec-type int[]
    rep-type hashcode
    comparability 7
  variable ::Positive_RA_Alt_Thresh[..]
    var-kind array
    enclosing-var ::Positive_RA_Alt_Thresh
    array 1
    dec-type int[]
    rep-type int[]
    comparability 8[6]
  variable ::Up_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 8
  variable ::Down_Separation
    var-kind variable
    dec-type int
    rep-type int
    comparability 8
  variable ::Other_RAC
    var-kind variable
    dec-type int
    rep-type int
    comparability 9
  variable ::Other_Capability
    var-kind variable
    dec-type int
    rep-type int
    comparability 10
  variable ::Climb_Inhibit
    var-kind variable
    dec-type int
    rep-type int
    comparability 11
  variable return
    var-kind return
    dec-type int
    rep-type int
    comparability 13

# Implicit Type to Explicit Type
#   1 : Cur_Vertical_Sep
#   2 : High_Confidence
#   3 : Two_of_Three_Reports_Valid
#   4 : Other_Tracked_Alt Own_Tracked_Alt
#   5 : Own_Tracked_Alt_Rate
#   6 : Alt_Layer_Value Positive_RA_Alt_Thresh_index
#   7 : Positive_RA_Alt_Thresh
#   8 : Down_Separation Positive_RA_Alt_Thresh_element Up_Separation
#   9 : Other_RAC
#  10 : Other_Capability
#  11 : Climb_Inhibit
#  12 : Down_Separation Positive_RA_Alt_Thresh_element Up_Separation lh_return_value
#  13 : lh_return_value
#  14 : argc
#  15 : argv
