package daikon.inv.unary.sequence;

import daikon.*;
import daikon.inv.*;
import daikon.inv.unary.sequence.*;
import daikon.inv.unary.scalar.*;
import daikon.inv.unary.*;
import daikon.inv.binary.sequenceScalar.*;
import daikon.inv.binary.twoSequence.*;
import daikon.derive.unary.*;
import utilMDE.*;

import java.util.*;

// *****
// Do not edit this file directly:
// it is automatically generated from Bound.java.jpp
// *****

// One reason not to combine LowerBound and Upperbound is that they have
// separate justifications:  one may be justified when the other is not.

// What should we do if there are few values in the range?
// This can make justifying that invariant easier, because with few values
// naturally there are more instances of each value.
// This might also make justifying that invariant harder, because to get more
// than (say) twice the expected number of samples (under the assumption of
// uniform distribution) requires many samples.
// Which of these dominates?  Is the behavior what I want?

public class EltUpperBound  extends SingleSequence  {

  // Variables starting with dkconfig_ should only be set via the
  // daikon.config.Configuration interface.
  public static boolean dkconfig_enabled = true;
  // If the bound is not within these constraints, then don't report it.
  // For instance, these could be set to -1 and 2 to only permit output
  // of bounds in the range (-1,0,1,2).
  public static long dkconfig_minimal_interesting = Long.MIN_VALUE;
  public static long dkconfig_maximal_interesting = Long.MAX_VALUE;

  public UpperBoundCore  core;

  private EltUpperBound (PptSlice ppt) {
    super(ppt);
    core = new UpperBoundCore (this);
  }

  public static EltUpperBound  instantiate(PptSlice ppt) {
    if (!dkconfig_enabled) return null;
    return new EltUpperBound (ppt);
  }

  public String repr() {
    return "EltUpperBound"  + varNames() + ": "
      + core.repr();
  }

  // ELTLOWEr || ELTUPPEr
  public String format() {
    return var().name.name() + " elements <= " + core.max1 ;
  }

  public String format_esc() {
    String[] form =
      VarInfoName.QuantHelper.format_esc(new VarInfoName[]
	{ var().name });
    return form[0] + "(" + form[1] + " <= " + core.max1  + ")" + form[2];
  }

  public String format_ioa(String classname) {
    String form[] = VarInfoName.QuantHelper.format_ioa(new VarInfo[] {var()},
						       classname);
    String result = form[0]+form[1]+" "+ "<" +"= "+ core.max1 +form[2];
    return result;
  }

  public String format_simplify() {
    String[] form =
      VarInfoName.QuantHelper.format_simplify(new VarInfoName[]
	{ var().name });
    return form[0] + "(<= " + form[1] + " " + core.max1  + ")" + form[2];
  }

  public void add_modified(long[]  value, int count) {
    // System.out.println("EltUpperBound"  + varNames() + ": "
    //                    + "add(" + value + ", " + modified + ", " + count + ")");

    for (int i=0; i<value.length; i++) {
      core.add_modified(value[i], count);
      if (no_invariant)
        return;
    }

  }

  public boolean enoughSamples() {
    return core.enoughSamples();
  }

  protected double computeProbability() {
    return core.computeProbability();
  }

  public boolean isExact() {
    return core.isExact();
  }

  public boolean isSameFormula(Invariant other)
  {
    return core.isSameFormula(((EltUpperBound ) other).core);
  }

  public boolean isObviousImplied() {
    // if the value is not in some range (like -1,0,1,2) then say that it is obvious
    if ((core.max1  < dkconfig_minimal_interesting) ||
	(core.max1  > dkconfig_maximal_interesting)) {
      return true;
    }
    EltOneOf  oo = EltOneOf .find(ppt);
    if ((oo != null) && oo.enoughSamples()) {
      // Equivalently, core.max1  > = oo. min_elt ()
      if (! (((Long)oo. min_elt ()).longValue() <  core.max1 )) {
        return true;
      }
    }

    return super.isObviousImplied();
  }

  public boolean isObviousDerived() {
    VarInfo v = var();
    if (v.isDerived() && (v.derived instanceof SequenceLength)) {
      int vshift = ((SequenceLength) v.derived).shift;
      if (vshift != 0) {
        return true;

      }
    }

    // For each sequence variable, if this is an obvious member/subsequence, and
    // it has the same invariant, then this one is obvious.
    PptTopLevel pptt = (PptTopLevel) ppt.parent;
    for (int i=0; i<pptt.var_infos.length; i++) {
      VarInfo vi = pptt.var_infos[i];

      if (SubSequence.isObviousDerived(v, vi))

      {
        PptSlice1 other_slice = pptt.findSlice(vi);
        if (other_slice != null) {
          EltUpperBound  eb = EltUpperBound .find(other_slice);
          if ((eb != null)
              && eb.enoughSamples()
              && eb. core.max1  == core.max1 ) {
            return true;
          }
        }
      }
    }

    return false;
  }

  public boolean isExclusiveFormula(Invariant other) {
    if (other instanceof EltLowerBound ) {
      if (core.max1  <  ((EltLowerBound ) other). core.min1 )
        return true;
    }
    if (other instanceof OneOfScalar) {
      return other.isExclusiveFormula(this);
    }
    return false;
  }

  // Look up a previously instantiated invariant.
  public static EltUpperBound  find(PptSlice ppt) {
    Assert.assert(ppt.arity == 1);
    for (Iterator itor = ppt.invs.iterator(); itor.hasNext(); ) {
      Invariant inv = (Invariant) itor.next();
      if (inv instanceof EltUpperBound )
        return (EltUpperBound ) inv;
    }
    return null;
  }

}

