#! /bin/sh

# CHANGES-spellcheck
# no arguments

# Passes the most recent part of the CHANGES file
# to hunspell for spell checking.

# Note that this is not very sophisticated:
# 1) defines 'recent' as just the first 100 lines
# 2) assumes any line starting with four or more 
#    spaces is literal text not to be checked.

# There are likely to be several false positives!

# -u switch to hunspell is undocumented and subject to change,
# but gives a line number whereas -l does not.

head -100 CHANGES | sed 's/^    .*/ /' | hunspell -u -p daikon.dict "$@"

