default:
	@echo "Specify a target:"
	@echo "  www-dist pag-install"

# Not the default to avoid accidentally installing new webpages.
www-dist:
	cd .. && $(MAKE) www-dist
pag-install:
	cd .. && $(MAKE) pag-install
