decl-version 2.0

var-comparability implicit

ppt std.enqueue(int;process\_*;)int:::ENTER
  ppt-type enter
  variable prio
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2

ppt std.enqueue(int;process\_*;)int:::EXIT1
  ppt-type subexit
  variable prio
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2
  variable return
    var-kind return
    dec-type int
    rep-type int
    comparability 3

ppt std.enqueue(int;process\_*;)int:::EXIT2
  ppt-type subexit
  variable prio
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2
  variable return
    var-kind return
    dec-type int
    rep-type int
    comparability 3

ppt std.main(int;char\_**;)int:::ENTER
  ppt-type enter
  variable argc
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable argv
    var-kind variable
    dec-type char\_*[]
    rep-type hashcode
    comparability 5
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2

ppt std.main(int;char\_**;)int:::EXIT3
  ppt-type subexit
  variable argc
    var-kind variable
    dec-type int
    rep-type int
    comparability 4
  variable argv
    var-kind variable
    dec-type char\_*[]
    rep-type hashcode
    comparability 5
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2
  variable return
    var-kind return
    dec-type int
    rep-type int
    comparability 3

ppt std.get_command(int\_*;int\_*;float\_*;)int:::ENTER
  ppt-type enter
  variable command
    var-kind variable
    dec-type int[]
    rep-type hashcode
    comparability 6
  variable *command
    var-kind variable
    dec-type int
    rep-type int
    comparability 7
  variable prio
    var-kind variable
    dec-type int[]
    rep-type hashcode
    comparability 1
  variable *prio
    var-kind variable
    dec-type int
    rep-type int
    comparability 7
  variable ratio
    var-kind variable
    dec-type float[]
    rep-type hashcode
    comparability 8
  variable *ratio
    var-kind variable
    dec-type float
    rep-type double
    comparability 9
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2

ppt std.get_command(int\_*;int\_*;float\_*;)int:::EXIT4
  ppt-type subexit
  variable command
    var-kind variable
    dec-type int[]
    rep-type hashcode
    comparability 6
  variable *command
    var-kind variable
    dec-type int
    rep-type int
    comparability 7
  variable prio
    var-kind variable
    dec-type int[]
    rep-type hashcode
    comparability 1
  variable *prio
    var-kind variable
    dec-type int
    rep-type int
    comparability 7
  variable ratio
    var-kind variable
    dec-type float[]
    rep-type hashcode
    comparability 8
  variable *ratio
    var-kind variable
    dec-type float
    rep-type double
    comparability 9
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2
  variable return
    var-kind return
    dec-type int
    rep-type int
    comparability 3

ppt std.get_command(int\_*;int\_*;float\_*;)int:::EXIT5
  ppt-type subexit
  variable command
    var-kind variable
    dec-type int[]
    rep-type hashcode
    comparability 6
  variable *command
    var-kind variable
    dec-type int
    rep-type int
    comparability 7
  variable prio
    var-kind variable
    dec-type int[]
    rep-type hashcode
    comparability 1
  variable *prio
    var-kind variable
    dec-type int
    rep-type int
    comparability 7
  variable ratio
    var-kind variable
    dec-type float[]
    rep-type hashcode
    comparability 8
  variable *ratio
    var-kind variable
    dec-type float
    rep-type double
    comparability 9
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2
  variable return
    var-kind return
    dec-type int
    rep-type int
    comparability 3

ppt std.exit_here(int;)int:::ENTER
  ppt-type enter
  variable status
    var-kind variable
    dec-type int
    rep-type int
    comparability 10
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2

ppt std.exit_here(int;)int:::EXIT6
  ppt-type subexit
  variable status
    var-kind variable
    dec-type int
    rep-type int
    comparability 10
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2
  variable return
    var-kind return
    dec-type int
    rep-type int
    comparability 3

ppt std.new_job(int;)int:::ENTER
  ppt-type enter
  variable prio
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2

ppt std.new_job(int;)int:::EXIT7
  ppt-type subexit
  variable prio
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2
  variable return
    var-kind return
    dec-type int
    rep-type int
    comparability 3

ppt std.upgrade_prio(int;float;)int:::ENTER
  ppt-type enter
  variable prio
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ratio
    var-kind variable
    dec-type float
    rep-type double
    comparability 8
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2

ppt std.upgrade_prio(int;float;)int:::EXIT8
  ppt-type subexit
  variable prio
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ratio
    var-kind variable
    dec-type float
    rep-type double
    comparability 8
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2
  variable return
    var-kind return
    dec-type int
    rep-type int
    comparability 3

ppt std.upgrade_prio(int;float;)int:::EXIT9
  ppt-type subexit
  variable prio
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ratio
    var-kind variable
    dec-type float
    rep-type double
    comparability 8
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2
  variable return
    var-kind return
    dec-type int
    rep-type int
    comparability 3

ppt std.upgrade_prio(int;float;)int:::EXIT10
  ppt-type subexit
  variable prio
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ratio
    var-kind variable
    dec-type float
    rep-type double
    comparability 8
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2
  variable return
    var-kind return
    dec-type int
    rep-type int
    comparability 3

ppt std.block()int:::ENTER
  ppt-type enter
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2

ppt std.block()int:::EXIT11
  ppt-type subexit
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2
  variable return
    var-kind return
    dec-type int
    rep-type int
    comparability 3

ppt std.block()int:::EXIT12
  ppt-type subexit
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2
  variable return
    var-kind return
    dec-type int
    rep-type int
    comparability 3

ppt std.unblock(float;)int:::ENTER
  ppt-type enter
  variable ratio
    var-kind variable
    dec-type float
    rep-type double
    comparability 8
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2

ppt std.unblock(float;)int:::EXIT13
  ppt-type subexit
  variable ratio
    var-kind variable
    dec-type float
    rep-type double
    comparability 8
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2
  variable return
    var-kind return
    dec-type int
    rep-type int
    comparability 3

ppt std.unblock(float;)int:::EXIT14
  ppt-type subexit
  variable ratio
    var-kind variable
    dec-type float
    rep-type double
    comparability 8
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2
  variable return
    var-kind return
    dec-type int
    rep-type int
    comparability 3

ppt std.quantum_expire()int:::ENTER
  ppt-type enter
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2

ppt std.quantum_expire()int:::EXIT15
  ppt-type subexit
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2
  variable return
    var-kind return
    dec-type int
    rep-type int
    comparability 3

ppt std.quantum_expire()int:::EXIT16
  ppt-type subexit
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2
  variable return
    var-kind return
    dec-type int
    rep-type int
    comparability 3

ppt std.finish()int:::ENTER
  ppt-type enter
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2

ppt std.finish()int:::EXIT17
  ppt-type subexit
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2
  variable return
    var-kind return
    dec-type int
    rep-type int
    comparability 3

ppt std.finish()int:::EXIT18
  ppt-type subexit
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2
  variable return
    var-kind return
    dec-type int
    rep-type int
    comparability 3

ppt std.flush()int:::ENTER
  ppt-type enter
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2

ppt std.flush()int:::EXIT19
  ppt-type subexit
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2
  variable return
    var-kind return
    dec-type int
    rep-type int
    comparability 3

ppt std.get_current()process\_*:::ENTER
  ppt-type enter
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2

ppt std.get_current()process\_*:::EXIT20
  ppt-type subexit
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2

ppt std.reschedule(int;)int:::ENTER
  ppt-type enter
  variable prio
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2

ppt std.reschedule(int;)int:::EXIT21
  ppt-type subexit
  variable prio
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2
  variable return
    var-kind return
    dec-type int
    rep-type int
    comparability 3

ppt std.schedule(int;int;float;)int:::ENTER
  ppt-type enter
  variable command
    var-kind variable
    dec-type int
    rep-type int
    comparability 11
  variable prio
    var-kind variable
    dec-type int
    rep-type int
    comparability 11
  variable ratio
    var-kind variable
    dec-type float
    rep-type double
    comparability 8
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2

ppt std.schedule(int;int;float;)int:::EXIT22
  ppt-type subexit
  variable command
    var-kind variable
    dec-type int
    rep-type int
    comparability 11
  variable prio
    var-kind variable
    dec-type int
    rep-type int
    comparability 11
  variable ratio
    var-kind variable
    dec-type float
    rep-type double
    comparability 8
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2
  variable return
    var-kind return
    dec-type int
    rep-type int
    comparability 3

ppt std.put_end(int;process\_*;)int:::ENTER
  ppt-type enter
  variable prio
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2

ppt std.put_end(int;process\_*;)int:::EXIT23
  ppt-type subexit
  variable prio
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2
  variable return
    var-kind return
    dec-type int
    rep-type int
    comparability 3

ppt std.put_end(int;process\_*;)int:::EXIT24
  ppt-type subexit
  variable prio
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2
  variable return
    var-kind return
    dec-type int
    rep-type int
    comparability 3

ppt std.get_process(int;float;process\_**;)int:::ENTER
  ppt-type enter
  variable prio
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ratio
    var-kind variable
    dec-type float
    rep-type double
    comparability 8
  variable job
    var-kind variable
    dec-type process\_*[]
    rep-type hashcode
    comparability 12
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2

ppt std.get_process(int;float;process\_**;)int:::EXIT25
  ppt-type subexit
  variable prio
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ratio
    var-kind variable
    dec-type float
    rep-type double
    comparability 8
  variable job
    var-kind variable
    dec-type process\_*[]
    rep-type hashcode
    comparability 12
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2
  variable return
    var-kind return
    dec-type int
    rep-type int
    comparability 3

ppt std.get_process(int;float;process\_**;)int:::EXIT26
  ppt-type subexit
  variable prio
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ratio
    var-kind variable
    dec-type float
    rep-type double
    comparability 8
  variable job
    var-kind variable
    dec-type process\_*[]
    rep-type hashcode
    comparability 12
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2
  variable return
    var-kind return
    dec-type int
    rep-type int
    comparability 3

ppt std.get_process(int;float;process\_**;)int:::EXIT27
  ppt-type subexit
  variable prio
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ratio
    var-kind variable
    dec-type float
    rep-type double
    comparability 8
  variable job
    var-kind variable
    dec-type process\_*[]
    rep-type hashcode
    comparability 12
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2
  variable return
    var-kind return
    dec-type int
    rep-type int
    comparability 3

ppt std.get_process(int;float;process\_**;)int:::EXIT28
  ppt-type subexit
  variable prio
    var-kind variable
    dec-type int
    rep-type int
    comparability 1
  variable ratio
    var-kind variable
    dec-type float
    rep-type double
    comparability 8
  variable job
    var-kind variable
    dec-type process\_*[]
    rep-type hashcode
    comparability 12
  variable ::next_pid
    var-kind variable
    dec-type int
    rep-type int
    comparability 2
  variable return
    var-kind return
    dec-type int
    rep-type int
    comparability 3

# Implicit Type to Explicit Type
#   1 : prio
#   2 : next_pid
#   3 : lh_return_value
#   4 : argc
#   5 : argv
#   6 : command
#   7 : *command *prio
#   8 : ratio
#   9 : *ratio
#  10 : status
#  11 : command prio
#  12 : job
