###########################################################################

# Read Makefile.common for what all of this means

MAIN_CLASS:=javautil.ArrayListTest

include ../../Makefile.common

instrument-files-revise:
	echo "javautil/AbstractList.java javautil/ArrayList.java" >| ${INST_LIST_FILE}
