###########################################################################

# Read Makefile.common for what all of this means

MAIN_CLASS:=PolyCalc.PublicTest
INST_FILES = PolyCalc.Cons$$|PolyCalc.RatPolyStack$$

ESC_ON:=1

include ../../Makefile.common

instrument-files-revise:
	echo "PolyCalc/RatPolyStack.java" >| ${INST_LIST_FILE}
