###########################################################################

# Read Makefile.common for what all of this means
# Test for handling of parameter variables in method invocations.

MAIN_CLASS:=misc.Param
PROJECT_FILE:=Param
INST_FILES = ^misc.Param

ESC_ON:=1

include ../../Makefile.common
