###########################################################################

# Read Makefile.common for what all of this means

MAIN_CLASS:=misc.Compar1
PROJECT_FILE:=Compar1

ESC_ON:=1

include ../../Makefile.common

instrument-files-revise:
	rm -f ${INST_LIST_FILE}
	echo "misc/Compar1.java" > ${INST_LIST_FILE}
