###########################################################################

# Read Makefile.common for what all of this means

#MAIN_CLASS:=javautil.VectorTest
MAIN_CLASS:=javautil.VectorTestDeterministic13
#MAIN_CLASS:=javautil.VectorTestAug

ESC_ON:=1

include ../../Makefile.common

#USER_CLUSTER_OPTIONS:=-a km -k 5

instrument-files-revise:
	echo "javautil/Vector13.java" >| ${INST_LIST_FILE}
