//
// Generated by JTB 1.2.2
//

package jtb.syntaxtree;

/**
 * Grammar production:
 * f0 -> "new" PrimitiveType() ArrayDimsAndInits()
 *       | "new" Name() ( ArrayDimsAndInits() | Arguments() [ ClassBody() ] )
 */
public class AllocationExpression implements Node {
   private Node parent;
   public NodeChoice f0;

   public AllocationExpression(NodeChoice n0) {
      f0 = n0;
      if ( f0 != null ) f0.setParent(this);
   }

   public void accept(jtb.visitor.Visitor v) {
      v.visit(this);
   }
   public Object accept(jtb.visitor.ObjectVisitor v, Object argu) {
      return v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

