#!/bin/sh

# Used by the cron job that runs as user daikonbuildtest
# Removes all build subdirectories older than 7 days

cd $HOME/build
find . -name "[[:digit:]]*" -type d -maxdepth 1 -mtime +7 -exec rm -r {} \;


