#!/bin/sh

# Used by the cron job that runs as user daikonuser

# How to setup an account for nightly build/test:
# 1. Create user named 'daikonuser'
# 2. Login as user 'daikonuser'
# 3. `mkdir $HOME/build $HOME/research`
# 4. `cd $HOME/research`
# 5. `cvs -d $CVS_REPOSITORY co invariants/scripts`
# 6. `crontab $HOME/research/invariants/scripts/buildtest.crontab`
cd $HOME/build
exec /usr/bin/env perl $HOME/research/invariants/scripts/buildtest.pl --quiet $*
