#!/usr/bin/env perl
use strict;
use English;
$WARNING = 1;

my $build_dir = "/afs/csail.mit.edu/u/d/daikonuser/build";
my $build_dir_exists = -d $build_dir;
my $build_dir_age = -M $build_dir;
if ((! $build_dir_exists) || ($build_dir_age > 1)) {
  system('echo "~buildtest-check says: Directory ~daikonuser/build has not been recently updated.  Perhaps overnight tests failed to run?" | mail -s "buildtest-check: Problem with Daikon build tests" mernst@cs.washington.edu,jhp@csail.mit.edu');
}
