#!/bin/sh

die()
{
    echo "`basename $0`: $1" >&2
    exit 1
}

chdir()
{
    cd $1 >/dev/null 2>&1
    [ `realpath \`pwd\`` = `realpath "$1"` ] || die "can't chdir to $1."
}

[ -z "$INV" ] && INV="$inv"
[ -z "$INV" ] && INV=$HOME/research/invariants

[ -d "$INV" ] || die "can't find \$INV dir: \`$INV'."

chdir $INV

[ -d "$INV/bugs" ] || die "no dir $INV/bugs."

chdir $INV/bugs

[ -x ./bugtrack ] || die "bugtrack script not found in $INV/bugs."

exec ./bugtrack "$@"

