# Create a Docker image that is ready to run the Daikon tests.

FROM rockylinux:9
LABEL org.opencontainers.image.authors="Michael Ernst <mernst@cs.washington.edu>"

# According to
# https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/:
#  * Put "apt-get update" and "apt-get install" in the same RUN command.
#  * Do not run "apt-get upgrade"; instead get upstream to update.

# The EPEL repository contains certain packages.
RUN dnf -q -y upgrade && dnf -q -y install \
  epel-release

# curl is installed by default on Rocky Linux.
RUN dnf -q -y upgrade && dnf -q -y install \
  autoconf \
  automake \
  bc \
  binutils-devel \
  diffutils \
  findutils \
  gcc \
  git \
  jq \
  libxcrypt-devel \
  m4 \
  make \
  perl-English \
  perl-filetest \
  rsync \
  tar \
  unzip \
  wget \
  which

# Install the JDK.
## Use this once the java-27-openjdk* packages exist.
# RUN dnf -q -y upgrade && dnf -q -y install \
#   java-27-openjdk \
#   java-27-openjdk-devel
# ENV JAVA27_HOME=/usr/lib/jvm/java-27

# The java-27-openjdk* packages do not yet exist, so download the JDK.
# RUN curl --silent -o jdk-27_linux-x64_bin.tar.gz https://download.oracle.com/java/27/latest/jdk-27_linux-x64_bin.tar.gz \
RUN curl --silent -o jdk-27_linux-x64_bin.tar.gz https://download.java.net/java/GA/jdk27/55ce5470a6294008af0057ff4626d0e5/35/GPL/openjdk-27_linux-x64_bin.tar.gz \
&& tar xzf jdk-27_linux-x64_bin.tar.gz \
&& rm jdk-27_linux-x64_bin.tar.gz
ENV PATH="/jdk-27/bin:/root/.local/bin:/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
ENV JAVA27_HOME=/jdk-27
RUN chmod og+rx /root \
&& chmod og+r /root/*

# Clean up.
RUN dnf -q clean all
