This directory contains Dockerfiles to create new Docker images for
running Daikon tests reproducibly.

The rest of this file explains how to build new Docker images:


Preliminaries:

  # Finish docker setup if necessary.
  sudo usermod -aG docker $(whoami)
  # Then log out and back in.

  # Obtain Docker credentials.
  # (This is only necessary once per machine; credentials are cached.)
  docker login


Create the Docker image:

# Alias to create the Docker image, in an empty directory, and upload to Docker Hub.
# Takes about 12 minutes for jdk8, about 1 hour for jdk8-plus.
# Run from a terminal, NOT from Emacs, because it produces vast amounts of output.
DOCKERTESTING=""
# DOCKERTESTING="-testing"
alias create_upload_docker_image=' \
  DOCKERIMAGE="mdernst/$DPROJECT-$OS-$JDKVER$DOCKERTESTING" && \
  (rm -rf dockerdir && \
  mkdir -p dockerdir && \
  (cd dockerdir && \
  \cp -pf ../Dockerfile-$OS-$JDKVER Dockerfile && \
  docker build -t $DOCKERIMAGE . && \
  docker push $DOCKERIMAGE) && \
  rm -rf dockerdir) || \
  (echo "*****"; echo "*****"; echo "FAILURE in $DOCKERIMAGE"; echo "*****"; echo "*****"; false) \
'

export OS=ubuntu
export JDKVER=jdk8
export DPROJECT=daikon
create_upload_docker_image

export OS=ubuntu
export JDKVER=jdk8-plus
export DPROJECT=daikon
create_upload_docker_image

export OS=ubuntu
export JDKVER=jdk11
export DPROJECT=daikon
create_upload_docker_image

export OS=ubuntu
export JDKVER=jdk11-plus
export DPROJECT=daikon
create_upload_docker_image

export OS=ubuntu
export JDKVER=jdk17
export DPROJECT=daikon
create_upload_docker_image

export OS=ubuntu
export JDKVER=jdk17-plus
export DPROJECT=daikon
create_upload_docker_image

export OS=ubuntu
export JDKVER=jdk20
export DPROJECT=daikon
create_upload_docker_image

export OS=ubuntu
export JDKVER=jdk20-plus
export DPROJECT=daikon
create_upload_docker_image

export OS=ubuntu
export JDKVER=jdk21
export DPROJECT=daikon
create_upload_docker_image

export OS=ubuntu
export JDKVER=jdk21-plus
export DPROJECT=daikon
create_upload_docker_image

export OS=rockylinux
export JDKVER=jdk8
export DPROJECT=daikon
create_upload_docker_image

export OS=rockylinux
export JDKVER=jdk8-plus
export DPROJECT=daikon
create_upload_docker_image

export OS=rockylinux
export JDKVER=jdk11
export DPROJECT=daikon
create_upload_docker_image

export OS=rockylinux
export JDKVER=jdk11-plus
export DPROJECT=daikon
create_upload_docker_image

export OS=rockylinux
export JDKVER=jdk17
export DPROJECT=daikon
create_upload_docker_image

export OS=rockylinux
export JDKVER=jdk17-plus
export DPROJECT=daikon
create_upload_docker_image

export OS=rockylinux
export JDKVER=jdk21
export DPROJECT=daikon
create_upload_docker_image

export OS=rockylinux
export JDKVER=jdk21-plus
export DPROJECT=daikon
create_upload_docker_image

Cleanup:

docker image prune && docker images | grep none | awk '{ print $3; }' | xargs --no-run-if-empty docker rmi --force

To stop and remove/delete *all* docker containers:
  docker stop $(docker ps -a -q)
  docker rm $(docker ps -a -q)
