m4_dnl Definitions shared by Dockerfile-ubuntu.m4 and Dockerfile-rockylinux.m4.
m4_dnl Run m4 with the -P command-line option, so built-in macros are prefixed by "m4_".
m4_dnl The caller defines these macros on the command line:
m4_dnl   JDKVER: the JDK version, such as 21
m4_dnl   PLUS: 1 for a "-plus" image (which contains more tools), 0 otherwise
m4_changequote([[,]])m4_dnl
m4_dnl Disable comments, so that macros are expanded within "#" comments.
m4_changecom()m4_dnl
m4_dnl jdk_at_least(N) expands to 1 if JDKVER >= N, and to 0 otherwise.
m4_define([[jdk_at_least]], [[m4_eval(JDKVER >= $1)]])m4_dnl
m4_dnl jdk_lts expands to 1 if JDKVER is a long-term-support (LTS) release, and to 0 otherwise.
m4_define([[jdk_lts]], [[m4_eval(JDKVER == 8 || JDKVER == 11 || JDKVER == 17 || (JDKVER >= 21 && (JDKVER - 21) % 4 == 0))]])m4_dnl
m4_dnl jdk_packaged_ubuntu expands to 1 if Ubuntu provides the openjdk-JDKVER-jdk package,
m4_dnl and to 0 otherwise.  When it is 0, the JDK is downloaded from jdk_download_url.
m4_define([[jdk_packaged_ubuntu]], [[m4_eval(JDKVER < 27)]])m4_dnl
m4_dnl rockylinux_newest_packaged_jdk is the newest JDK that Rocky Linux provides as an OS package.
m4_define([[rockylinux_newest_packaged_jdk]], [[25]])m4_dnl
m4_dnl jdk_packaged_rockylinux expands to 1 if Rocky Linux provides the java-JDKVER-openjdk package,
m4_dnl and to 0 otherwise.  When it is 0, the JDK is downloaded from jdk_download_url.
m4_dnl Rocky Linux packages only LTS JDKs.  For a non-LTS JDK, dnf satisfies java-JDKVER-openjdk with
m4_dnl EPEL's java-latest-openjdk, which moves to a newer JDK whenever the image is rebuilt.
m4_define([[jdk_packaged_rockylinux]], [[m4_eval(jdk_lts && JDKVER <= rockylinux_newest_packaged_jdk)]])m4_dnl
m4_define([[jdk_download_url]], [[https://download.java.net/java/GA/jdk27/55ce5470a6294008af0057ff4626d0e5/35/GPL/openjdk-27_linux-x64_bin.tar.gz]])m4_dnl
m4_dnl if_plus(TEXT) expands to TEXT for a "-plus" image, and to nothing otherwise.
m4_define([[if_plus]], [[m4_ifelse(PLUS, 1, [[$1]])]])m4_dnl
m4_dnl The comment at the top of each generated Dockerfile.
m4_define([[dockerfile_header]], [[# DO NOT EDIT this file.  Edit $1 instead.

m4_ifelse(PLUS, 1, [[# Create a Docker image that is ready to run the full Daikon tests,
# including building the manual and Javadoc.
# But it's used primarily for running miscellaneous tests such as the manual
# and Javadoc.]], [[# Create a Docker image that is ready to run the Daikon tests.]])]])m4_dnl
