# Create a Docker image that is ready to run the Daikon tests,
# using JDK 8.

FROM fedora
MAINTAINER Michael Ernst <mernst@cs.washington.edu>

# According to
# https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/:
#  * Put "apt-get update" and "apt-get install" in the same RUN command.
#  * Do not run "apt-get upgrade"; instead get upstream to update.
RUN dnf -qy upgrade && dnf -qy install \
  autoconf \
  automake \
  bc \
  binutils-devel \
  gcc \
  git \
  jq \
  m4 \
  make \
  redhat-lsb \
  rsync \
  tar \
  unzip \
  which

RUN dnf -q -y install \
  java-11-openjdk \
  java-11-openjdk-devel

RUN dnf -q clean all
