# Create a Docker image that is ready to run the Daikon tests.

FROM rockylinux:9
LABEL org.opencontainers.image.authors="Michael Ernst <mernst@cs.washington.edu>"

# According to
# https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/:
#  * Put "apt-get update" and "apt-get install" in the same RUN command.
#  * Do not run "apt-get upgrade"; instead get upstream to update.

# The EPEL repository contains certain packages.
RUN dnf -q -y upgrade && dnf -q -y install \
  epel-release

# curl is installed by default on Rocky Linux.
RUN dnf -q -y upgrade && dnf -q -y install \
  autoconf \
  automake \
  bc \
  binutils-devel \
  diffutils \
  findutils \
  gcc \
  git \
  jq \
  libxcrypt-devel \
  m4 \
  make \
  perl-English \
  perl-filetest \
  rsync \
  tar \
  unzip \
  wget \
  which

# Install the JDK.
RUN dnf -q -y upgrade && dnf -q -y install \
  java-26-openjdk \
  java-26-openjdk-devel
ENV JAVA26_HOME=/usr/lib/jvm/java-26-openjdk

## Use this when the java-26-openjdk* packages don't yet exist.
# # RUN curl --silent -o jdk-26_linux-x64_bin.tar.gz https://download.oracle.com/java/26/latest/jdk-26_linux-x64_bin.tar.gz \
# RUN curl --silent -o jdk-26_linux-x64_bin.tar.gz https://download.java.net/java/GA/jdk26/bd75d5f9689641da8e1daabeccb5528b/36/GPL/openjdk-26_linux-x64_bin.tar.gz \
# && tar xzf jdk-26_linux-x64_bin.tar.gz
# ENV PATH="/jdk-26/bin:/root/.local/bin:/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
# ENV JAVA26_HOME=/jdk-26
# RUN chmod og+rx /root \
# && chmod og+r /root/*

# Clean up.
RUN dnf -q clean all
