This directory contains Dockerfiles to create new Docker images for
running Daikon tests reproducibly.
To build new Docker images:

  # Finish docker setup if necessary.
  sudo usermod -aG docker $(whoami)
  # Then log out and back in.

  # Obtain Docker credentials.
  # (This is only necessary once per machine; credentials are cached.)
  docker login

After running any of the below, consider deleting the docker containers,
which can take up a lot of disk space.
To stop and remove/delete all docker containers:
  docker stop $(docker ps -a -q)
  docker rm $(docker ps -a -q)
or you can just remove some of them.

# Create the Docker image, in an empty directory, and upload to Docker Hub.
# Takes about 12 minutes for jdk7 or jdk8, about 1 hour for jdkany.
alias create_upload_docker_image=' \
  rm -rf dockerdir && \
  mkdir -p dockerdir && \
  (cd dockerdir && \
  \cp -pf ../Dockerfile-$OS-$JDKVER Dockerfile && \
  docker build -t mdernst/$OS-for-$PROJECT-$JDKVER . && \
  docker push mdernst/$OS-for-$PROJECT-$JDKVER) && \
  rm -rf dockerdir'

export OS=ubuntu
export JDKVER=jdk7
export PROJECT=daikon
create_upload_docker_image

export OS=ubuntu
export JDKVER=jdk8
export PROJECT=daikon
create_upload_docker_image

export OS=ubuntu
export JDKVER=jdkany
export PROJECT=daikon
create_upload_docker_image

export OS=fedora
export JDKVER=jdk8
export PROJECT=daikon
create_upload_docker_image

export OS=fedora
export JDKVER=jdkany
export PROJECT=daikon
create_upload_docker_image

export OS=fedora24
export JDKVER=jdk8
export PROJECT=daikon
create_upload_docker_image

export OS=fedora24
export JDKVER=jdkany
export PROJECT=daikon
create_upload_docker_image

# export OS=fedora23
# export JDKVER=jdk8
# export PROJECT=daikon
# create_upload_docker_image
#
# export OS=fedora23
# export JDKVER=jdkany
# export PROJECT=daikon
# create_upload_docker_image

export OS=centos
export JDKVER=jdk8
export PROJECT=daikon
create_upload_docker_image

export OS=centos
export JDKVER=jdkany
export PROJECT=daikon
create_upload_docker_image
