# Create a Docker image that is ready to run the full Daikon tests,
# including building the manual and Javadoc.
# But it's used primarily for running miscellaneous tests such as the manual
# and Javadoc.

FROM centos
MAINTAINER Michael Ernst <mernst@cs.washington.edu>

# According to
# https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/:
#  * Put "apt-get update" and "apt-get install" in the same RUN command.
#  * Do not run "apt-get upgrade"; instead get upstream to update.
RUN dnf -q -y upgrade && dnf -q -y install \
  autoconf \
  automake \
  bc \
  binutils-devel \
  gcc \
  git \
  m4 \
  make \
  redhat-lsb \
  tar \
  unzip \
  which

RUN dnf -q -y install \
  java-11-openjdk \
  java-11-openjdk-devel

# This enables the repository that contains jq
RUN dnf -q -y install \
  epel-release

RUN dnf -q -y install \
  jq

RUN dnf -q -y install \
  ctags \
  curl \
  ctags \
  gcc-c++ \
  graphviz \
  netpbm \
  python2 \
  python3 \
  rsync \
  texlive \
  wget

# Make default be Python 2, for backward compatibility just in case.
RUN alternatives --set python /usr/bin/python2

## Texinfo has been removed from the main repositories as of CentOS 8.
RUN dnf -y install --skip-broken \
  http://mirror.centos.org/centos/8/PowerTools/x86_64/os/Packages/texi2html-5.0-8.el8.noarch.rpm \
  http://mirror.centos.org/centos/8/PowerTools/x86_64/os/Packages/texinfo-6.5-4.el8.x86_64.rpm \
  http://mirror.centos.org/centos/8/PowerTools/x86_64/os/Packages/texinfo-tex-6.5-4.el8.x86_64.rpm

RUN dnf -q clean all
