# Create a Docker image that is ready to run the Daikon tests,
# using JDK 8.

FROM ubuntu
MAINTAINER Michael Ernst <mernst@cs.washington.edu>

# According to
# https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/:
#  * Put "apt-get update" and "apt-get install" in the same RUN command.
#  * Do not run "apt-get upgrade"; instead get upstream to update.
RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get -qqy update \
&& apt-get -qqy install \
  autoconf \
  automake \
  bc \
  binutils-dev \
  ctags \
  gcc \
  git \
  graphviz \
  m4 \
  make \
  netpbm \
  unzip \
  default-jdk \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get -qqy update \
&& apt-get -qqy install \
  openjdk-8-jdk \
&& update-java-alternatives --set java-1.8.0-openjdk-amd64 \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

# These are needed to build the Checker Framework, used by the "typecheck" job in CI.
RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get -qqy update \
&& apt-get -qqy install \
  ant \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*
