#! /bin/csh -f
# prints the full path of the dtrace file for the specified program.
# Looks first in the $DAIKONDIR/tests/daikon-tests/<prog> directory and then
# in /scratch/$user/tests/daikon-tests/<prog>_chicory.
set prog = $1
if (-e $DAIKONDIR/tests/daikon-tests/$prog/$prog.dtrace.gz) then
  echo $DAIKONDIR/tests/daikon-tests/$prog/$prog.dtrace.gz \
    $DAIKONDIR/tests/daikon-tests/$prog/*.decls
else
  echo /scratch/$USER/tests/daikon-tests/${prog}_chicory/$prog.dtrace.gz
endif
