#!/bin/sh
# prints the full path of the dtrace file for the specified program.
# Looks first in the $DAIKONDIR/tests/daikon-tests/<prog> directory and then
# in /scratch/$user/tests/daikon-tests/<prog>_chicory.

if [ $# -ne 1 ]; then
  echo "usage: $(basename "$0") PROGRAM" >&2
  exit 2
fi

prog=$1
if [ -e "$DAIKONDIR/tests/daikon-tests/$prog/$prog.dtrace.gz" ]; then
  # Expand the glob, but don't print it if it matches no file.
  set -- "$DAIKONDIR"/tests/daikon-tests/"$prog"/*.decls
  if [ -e "$1" ]; then
    echo "$DAIKONDIR/tests/daikon-tests/$prog/$prog.dtrace.gz" "$@"
  else
    echo "$DAIKONDIR/tests/daikon-tests/$prog/$prog.dtrace.gz"
  fi
else
  # $USER is not set in all environments (cron, su, containers).
  user=${USER:-$(id -un)}
  echo "/scratch/$user/tests/daikon-tests/${prog}_chicory/$prog.dtrace.gz"
fi
