#!/usr/bin/perl -p -i
# (When debugging, change "-i" to "-i.bak" above.)
# Michael Ernst <mernst@cs.washington.edu>

# This supports the Emacs function `jdk-goto-ref' by inserting, into HTML
# documentation, anchor names of the form received by Netscape from other
# processes such as Emacs.  After running this, re-rerun "jdk-index-to-alist".
# Run like this:
#   jdk-add-munged-anchor-names ${HOME}/java/OROMatcher-1.1/doc/api/*.html
#   jdk-add-munged-anchor-names ${HOME}/java/utilMDE/doc/utilMDE/*.html
#   jdk-add-munged-anchor-names `find ${HOME}/java/bobbyandjax/bobbydoc -name '*.html' -print`
#   jdk-add-munged-anchor-names ${HOME}/java/bobbyandjax/com/ibm/bobby/doc/*.html
#   jdk-add-munged-anchor-names `find ${HOME}/java/JavaClass/docs -name '*.html' -print`
#   jdk-add-munged-anchor-names `find ${HOME}/java/jakarta-log4j-1.2.7/docs -name '*.html' -print`
#   jdk-add-munged-anchor-names `find ${INV}/java/doc/ -name '*.html' -print`
#   jdk-add-munged-anchor-names `find ${HOME}/java/getopt-1.0.9/gnu/getopt/ -name '*.html' -print`
#   jdk-add-munged-anchor-names `find ${HOME}/java/jakarta-log4j-1.2.7/docs/ -name '*.html' -print`
# Full JDK (put "sudo" before "xargs", not before "find"):
#   find /usr/local/pkg/java/j2sdk1.4.1_01/docs/api -name '*.html' -print | xargs jdk-add-munged-anchor-names
#   find /g2/jdoc/jdk1.3/docs/api -name '*.html' -print | xargs jdk-add-munged-anchor-names

## Replaced by the use of FindBin.
# BEGIN {
#   unshift @INC, "$ENV{'INV'}/scripts";
# }
# use checkargs;

use FindBin ();
use lib "$FindBin::Bin";
use checkargs;

if ((/<A NAME=\"([^\"]*)\">(.*?)<\/A>/i) && ($1 =~ /[,\(\)]/))
 { s/(<A NAME=\")([^\"]*)(\">.*?<\/A>)/munge_duplicate_url($1,$2,$3)/ieg; }

sub munge_duplicate_url ( $$$ )
{ my ($pre, $url, $post) = check_args(3, @_);
  my $url_munged = $url;
  # This list of replacements is from Emacs's `browse-url-netscape' function.
  # (format "%%%x" (string-to-char ","))  ; "%2c"
  # (format "%%%x" (string-to-char "("))  ; "%28"
  # (format "%%%x" (string-to-char ")"))  ; "%29"
  $url_munged =~ s/,/%2c/g;
  $url_munged =~ s/\(/%28/g;
  $url_munged =~ s/\)/%29/g;
  return "<a name=\"$url_munged\">$pre$url$post</a>";
}
