#!/usr/bin/perl -pi
# Michael Ernst <mernst@cs.washington.edu>

# This supports the Emacs function `jdk-goto-ref' by inserting, into HTML
# documentation, anchor names of the form received by Netscape from other
# processes such as Emacs.
# Run like this:
#   jdk-add-munged-anchor-names `find /projects/cse/www/uns/doc/jdk1.2.2/api -name '*.html' -print`
#   jdk-add-munged-anchor-names ${HOME}/java/OROMatcher-1.1/doc/api/*.html
#   jdk-add-munged-anchor-names ${HOME}/java/utilMDE/doc/utilMDE/*.html
#   jdk-add-munged-anchor-names `find ${HOME}/java/bobbyandjax/bobbydoc -name '*.html' -print`
#   jdk-add-munged-anchor-names ${HOME}/java/bobbyandjax/com/ibm/bobby/doc/*.html
#   jdk-add-munged-anchor-names `find ${HOME}/java/JavaClass/docs -name '*.html' -print`
## Geyer
#    Argument list too long error:
#      jdk-add-munged-anchor-names `find /g2/jdoc/jdk1.3/docs/api -name '*.html' -print`
#    Alternate form:
#      find /g2/jdoc/jdk1.3/docs/api -name '*.html' -print | xargs jdk-add-munged-anchor-names

use checkargs;

if ((/<A NAME=\"([^\"]*)\">(.*?)<\/A>/i) && ($1 =~ /[,\(\)]/))
 { s/(<A NAME=\")([^\"]*)(\">.*?<\/A>)/munge_duplicate_url($1,$2,$3)/ieg; }

sub munge_duplicate_url ( $$$ )
{ my ($pre, $url, $post) = check_args(3, @_);
  my $url_munged = $url;
  # This list of replacements is from Emacs's `browse-url-netscape' function.
  # (format "%%%x" (string-to-char ","))  ; "%2c"
  # (format "%%%x" (string-to-char "("))  ; "%28"
  # (format "%%%x" (string-to-char ")"))  ; "%29"
  $url_munged =~ s/,/%2c/g;
  $url_munged =~ s/\(/%28/g;
  $url_munged =~ s/\)/%29/g;
  return "<a name=\"$url_munged\">$pre$url$post</a>";
}
