#!/bin/sh
if [ -z "$DAIKONDIR" ]; then
    DAIKONDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
    echo "Warning: environment variable DAIKONDIR is not set; using $DAIKONDIR"
fi 
if [ ! -d "$DAIKONDIR/kvasir" ]
then
    echo "Kvasir is not installed; to install it, run:    make -C \$DAIKONDIR kvasir"
    exit 1
fi
if [ ! -f "$DAIKONDIR/kvasir/valgrind/inst/bin/valgrind" ]
then
    echo "Kvasir is not built; to build it, run:    make -C \$DAIKONDIR kvasir"
    exit 1
fi
$DAIKONDIR/kvasir/valgrind/inst/bin/valgrind --tool=fjalar "$@"
