#!/usr/bin/perl -wn

# Print all lines after the first one that matches the pattern.
# Does a case-insensitive match.

BEGIN {
  $outputting = 0;
  $pattern = shift @ARGV;
}

if ($outputting) {
  print;
} elsif (/$pattern/io) {
  $outputting = 1;
  print;
}
