#! /bin/csh -fv
set path = ($inv/scripts $inv/plume-lib/bin $pag/software/pkg/jdk/bin /usr/local/bin/ /usr/local/csail/bin /bin /usr/bin /usr/X11R6/bin)
printenv JDK5DIR
/usr/bin/env perl $HOME/research/invariants/scripts/buildtest.pl --nocleanup $*
