###########################################################################

# Read Makefile.common for what all of this means

MAIN_CLASS:=DataStructures.DisjSetsTestMethodSequences
MAIN_ARGS:=4 3
PROJECT_FILE:=dsetsMS

include ../../../Makefile.common

instrument-files-revise:
	rm -f ${INST_LIST_FILE}
	echo "DataStructures/DisjSets.java" > ${INST_LIST_FILE}
