###########################################################################

# need junit.jar on classpath to compile all junit references
JUNIT_CLASSPATH := ${DAIKONDIR}/java/lib/*
JAVAC = ${CHECKED_JAVA_HOME}/bin/javac -cp .:$(JUNIT_CLASSPATH)
