###########################################################################

# need daikon.jar on classpath to compile all junit references
JAVAC := $(JAVA_HOME)/bin/javac -cp $(DAIKONDIR)/daikon.jar
