###########################################################################

# Read Makefile.common for what all of this means

MAIN_CLASS:=MyEvenOddTest
MAIN2_CLASS:=MyEvenOdd
JUNIT:=org.junit.runner.JUnitCore
NO_MERGE=1
NO_JML=1

# Override sources to draw from "."
SOURCES:=$(shell pwd)

include ../../Makefile.common

