NAME := ArraysInStructTest
#KVASIR_OPTIONS := --ppt-list-file=ArraysInStructTest.ppt
DAIKON_OPTIONS := --config_option daikon.DynamicConstants.OneOf_only=false --config_option daikon.inv.unary.scalar.OneOfScalar.enabled=0
include ../Makefile.common
