# Daikon test case from Madeline Hardojo at Nebraska.

# Read Makefile.common for what all of this means

TRACE_SOURCE           = stored
DECLS_FILES = pine_mdiep.decls.gz
OUTPUT_TYPE            = daikon

NO_JML=1
NO_MERGE=1

include ../../Makefile.common

#DAIKON_OPTIONS         := $(subst --suppress_redundant,,${DAIKON_OPTIONS})
#USER_DAIKON_OPTIONS    = --config config.txt
