// ***** This file is automatically generated from FunctionBinary.java.jpp

package daikon.inv.ternary.threeScalar;

import daikon.*;
import daikon.inv.Invariant;
import java.lang.reflect.*;
import org.apache.log4j.Category;

public class FunctionBinaryFloat 
  extends ThreeFloat 
{
  // We are Serializable, so we specify a version to allow changes to
  // method signatures without breaking serialization.  If you add or
  // remove fields, you should change this number to the current date.
  static final long serialVersionUID = 20020122L;

  // Variables starting with dkconfig_ should only be set via the
  // daikon.config.Configuration interface.
  /**
   * Boolean.  True iff FunctionBinaryFloat  invariants should be considered.
   **/
  public static boolean dkconfig_enabled = true;

  public static Category debug = Category.getInstance("daikon.inv.ternary.threeScalar." + "FunctionBinaryFloat" );

  public FunctionBinaryCoreFloat  core;

  protected FunctionBinaryFloat (PptSlice ppt, String methodname, int methodNumber, int var_order) {
    super(ppt);
    core = new FunctionBinaryCoreFloat (this, methodname, methodNumber, var_order);
  }

  public static FunctionBinaryFloat  instantiate(PptSlice ppt, String methodname, int methodNumber, int var_order) {
    if (!dkconfig_enabled) return null;

    {
      int[] indices = FunctionBinaryCoreFloat.var_indices[var_order];
      VarInfo argresult = ppt.var_infos[indices[0]];
      VarInfo arg1 = ppt.var_infos[indices[1]];
      VarInfo arg2 = ppt.var_infos[indices[2]];
      if (debug.isDebugEnabled())
        debug.debug("FunctionBinaryFloat"  + ".instantiate(" + ppt.name + ", "
                    + methodname + " (#" + methodNumber + "), "
                    + argresult.name + "="
                    + "f(" + arg1.name + "," + arg2.name + ")");
    }

    // SUPPRESS INVARIANT: if any var is constant, suppress FunctionBinaryFloat .
    // Skip if the arguments are constant (but not if the result is
    // constant, as we might get something like y=abs(x)).  (Actually, for
    // now I'm skipping if the result is constant, too: that's a
    // relationship over the two arguments, not a ternary relationship.)
    /* [INCR]
    int[] indices = FunctionBinaryCoreFloat.var_indices[var_order];
    VarInfo resultvar = ppt.var_infos[indices[0]];
    VarInfo arg1 = ppt.var_infos[indices[1]];
    VarInfo arg2 = ppt.var_infos[indices[2]];
    if (resultvar.isConstant() || (arg1.isConstant() && arg2.isConstant())) {
      debug.debug("FunctionBinaryFloat"  + ".instantiate: both args are constant");
      Global.subexact_noninstantiated_invariants++;
      return null;
    }
    */

    return new FunctionBinaryFloat (ppt, methodname, methodNumber, var_order);
  }

  protected Object clone() {
    FunctionBinaryFloat  result = (FunctionBinaryFloat) super.clone();
    result.core = (FunctionBinaryCoreFloat) core.clone();
    result.core.wrapper = result;
    return result;
  }

  protected Invariant resurrect_done(int[] permutation) {
    core.permute(permutation);
    return this;
  }

  public String repr() {
    return "FunctionBinaryFloat"   + varNames() + ": ";
  }

  public String format_using(OutputFormat format) {
    return core.format_using(format);
  }

  public void add_modified(double  x_int, double  y_int, double  z_int, int count) {
    core.add_modified(x_int, y_int, z_int, count);
  }

  protected double computeProbability() {
    return core.computeProbability();
  }

  public boolean isSameFormula(Invariant other)
  {
    return core.isSameFormula(((FunctionBinaryFloat) other).core);
  }

  // // For testing only; to be commented out
  // public void destroy() {
  //   if (debugFunctionBinary) {
  //     Method function = core.function;
  //     int var_order = core.var_order;
  //     int[] indices = FunctionBinaryCoreFloat.var_indices[var_order];
  //     VarInfo argresult = ppt.var_infos[indices[0]];
  //     VarInfo arg1 = ppt.var_infos[indices[1]];
  //     VarInfo arg2 = ppt.var_infos[indices[2]];
  //     System.out.println("CLASSNAME.destroy: "
  //                        + argresult.name + " = "
  //                        + function.getName() + "(" + arg1.name + ", " + arg2.name + ")");
  //   }
  //   super.destroy();
  // }

}
