###########################################################################

# Read Makefile.common for what all of this means

MAIN_CLASS:=misc.Precedence
PROJECT_FILE:=Precedence

ESC_ON:=1

include ../../Makefile.common

instrument-files-revise:
	rm -f ${INST_LIST_FILE}
	echo "misc/Precedence.java" > ${INST_LIST_FILE}
