name: Prek checks
"on": [push, pull_request]
jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: snap install circleci
      - run: echo "HOME=$HOME"
      - run: ls -al "$HOME"
      - run: ls -al /home
      - run: ls -al /home/runner
      - run: ls -al /home/runner/.config
      - run: ls -al /home/runner/.config/circleci
      - uses: j178/prek-action@v2

  prek_sudo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: sudo snap install circleci
      - run: echo "HOME=$HOME"
      - run: ls -al "$HOME"
      - run: ls -al /home
      - run: ls -al /home/runner
      - run: ls -al /home/runner/.config
      - run: ls -al /home/runner/.config/circleci
      - uses: j178/prek-action@v2
