name: Run CI tests

on: [push, pull_request]

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      JDK_OS: linux
      JDK_ARCH: x64
      JDK_VERSION: 24u22
      JDK_DIR: jdk-24.0.22
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        show-progress: false
    - name: Cache JDK
      uses: actions/cache@v4
      id: cache-jdk
      with:
        path: ~/.java
        key: jdk-${{ env.JDK_OS }}-${{ env.JDK_ARCH }}-${{ env.JDK_VERSION }}
    - name: Install JDK
      if: steps.cache-jdk.outputs.cache-hit != 'true'
      run: |
        export JDK_FILE="jdk-$JDK_VERSION-$JDK_OS-$JDK_ARCH.tar.gz"
        export JDK_URL="https://defects4j.org/downloads/$JDK_FILE"
        if [ ! -f "$JDK_FILE" ]; then mkdir -p ~/.java && (timeout 400 curl -O -s -S -L --retry 3 "$JDK_URL" || curl -O -L --retry 3 "$JDK_URL") && tar -xzf "$JDK_FILE" -C ~/.java; fi
    - name: Setup JDK
      run: |
        export JAVA_HOME=$HOME/.java/$JDK_DIR
        echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
        echo "$JAVA_HOME/bin" >> $GITHUB_PATH

- job: quick_txt_diff_ubuntu_jdk24
  - bash: ./scripts/test-quick-txt-diff.sh
    displayName: test-quick-txt-diff.sh

