###########################################################################

# Read Makefile.common for what all of this means

MAIN_CLASS:=misc.Smithnosky
PROJECT_FILE:=Smithnosky
INST_FILES = ^misc.

#ESC_ON:=1

include ../../Makefile.common

#instrument-files-revise:
